version: "3"

networks:
  redis-cluster:
    driver: bridge

services:
  redis7000:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7000:7000
    volumes:
      - ./7000/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis7001:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7001:7001
    volumes:
      - ./7001/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis7002:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7002:7002
    volumes:
      - ./7002/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis7003:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7003:7003
    volumes:
      - ./7003/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis7004:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7004:7004
    volumes:
      - ./7004/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster

  redis7005:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 7005:7005
    volumes:
      - ./7005/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis-cluster
